name: example
description: "A new Flutter project."

publish_to: 'none'
version: 0.0.1

environment:
  sdk: "3.2.2"
  flutter: "3.16.2"

dependencies:
  flutter:
    sdk: flutter

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: 7.6.4

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: 2.0.2+1

  crypto: 3.0.3

  qr_flutter: 4.1.0
  qr_code_scanner: 1.0.1
  qr_transfer:
    path: ../

  cryptography_utils:
    path: ../../cryptography_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: 2.4.6

flutter:
  uses-material-design: true