name: qr_transfer
description: "QR transfer (CBOR + UR)"
version: 0.0.2

environment:
  sdk: ">=3.2.2"

dependencies:
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  # CBOR library for Dart. An RFC8949 compliant encoding/decoding CBOR implementation.
  # https://pub.dev/packages/cbor
  cbor: 6.2.0

  # Implementations of SHA, MD5, and HMAC cryptographic functions.
  # https://pub:dev/packages/crypto
  crypto: 3.0.3

dev_dependencies:
  # A full featured library for writing and running Dart tests across platforms.
  # https://pub.dev/packages/test
  test: 1.25.5